class KomponenPC:
    def __init__(self, jenis, nama, harga, kompatibilitas):
        self.jenis = jenis
        self.nama = nama
        self.harga = harga
        self.kompatibilitas = kompatibilitas

def pilih_komponen(komponen_list, budget):
    total_harga = 0
    pilihan = []
    for komponen in komponen_list:
        if total_harga + komponen.harga <= budget:
            pilihan.append(komponen)
            total_harga += komponen.harga
    return pilihan

# Contoh penggunaan
komponen_list = [
    KomponenPC('CPU', 'Intel i5', 2000000, ['Motherboard A', 'Motherboard B']),
    KomponenPC('GPU', 'Nvidia GTX 1050', 1500000, ['Motherboard A']),
    KomponenPC('RAM', 'Kingston 8GB', 800000, ['Motherboard A', 'Motherboard B']),
]

budget = 5000000
pilihan = pilih_komponen(komponen_list, budget)
for p in pilihan:
    print(f"{p.jenis}: {p.nama} - Rp {p.harga}")
